version: "3.3"
services:
  db:
   image: mysql:8.0.19
   restart: always
   volumes:
    - db_data:/var/lib/mysql
   environment:
    - MYSQL_ROOT_PASSWORD=wordpress
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=john
  wordpress:
   image: wordpress:latest
   ports:
    - 80:80
   restart: always
   environment:
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=wordpress
     - WORDPRESS_DB_PASSWORD=john
     - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
